ScreenManager:
        Home_scr:
        Login_scr:
        User_Dashboard:
        Upcoming_Booking:
        Hall_selection:
        Account_setting:
        Help:
        Payment_scr:
        Past_booking:
        Seat_selection1:
        Seat_selection2:
<DrawerClickableItem@MDNavigationDrawerItem>
        focus_color:"800080"
        text_color:"00FFFF"
        selected_color:"FFD700"
<DrawerLabelItem@MDNavigationDrawerItem>
        focus_behavior:False
        text_color:"00FFFF"
<Home_scr>:
        name:"home"

        Image:
            #C://Users//asus//Documents//appsdevlopment using python//
                source:"liph.png"
                allow_stretch:True
                keep_ratio:False
        MDScreen:
                MDNavigationLayout:
                        MDScreenManager:
                                MDScreen:
                                        BoxLayout:
                                                orientation: 'vertical'
                                                MDTopAppBar:
                                                        title: "TMU Library Seat Booking"
                                                        md_bg_color:"#FFD700"
                                                        left_action_items: [["menu", lambda x: nav_drawer.set_state("open")]]
                                                        right_action_items: [["login", lambda x: app.switch_to_login()]]
                                                        elevation: 10
                                                MDFloatLayout:
                                                        #padding: "60dp"
                                                        spacing:'2dp'
                                                        MDCard:
                                                                orientation: 'vertical'
                                                                padding: "10dp"
                                                                size_hint_y: None
                                                                md_bg_color:1, 0.75, 0.0, 1
                                                                height: "100dp"
                                                                pos_hint:{'center_x':0.5,'center_y':0.88}
                                                                MDFloatLayout:
                                                                        MDLabel:
                                                                                text: "Reserve Your Study Spot Today!"
                                                                                pos_hint:{'center_y':0.9}
                                                                                halign: 'center'
                                                                                font_color:"#000000"
                                                                                font_style: "H5"

                                                                        MDRaisedButton:
                                                                                text: "Login"
                                                                                size_hint: None, None
                                                                                md_bg_color:"#FFD700"
                                                                                pos_hint:{'center_x':0.5,'center_y':0.5}
                                                                                size: "150dp", "40dp"
                                                                                on_press:app.switch_to_login()

                                                        MDCard:
                                                                orientation: 'vertical'
                                                                padding: "10dp"
                                                                size_hint: None, None
                                                                size: "100dp", "70dp"
                                                                md_bg_color:"#ADD8E6"
                                                                pos_hint:{"center_x":0.15,'center_y':0.68}

                                                                MDLabel:
                                                                        text: "Easy Booking"
                                                                        halign: 'center'
                                                                        font_style: "H6"
                                                                        color:"#000000"

                                                        MDCard:
                                                                orientation: 'vertical'
                                                                padding: "10dp"
                                                                size_hint: None, None
                                                                size: "120dp", "70dp"
                                                                md_bg_color:"0000FF"
                                                                pos_hint:{"center_x":0.42,'center_y':0.68}
                                                                MDLabel:
                                                                        text: "Real-Time Availability"
                                                                        halign: 'center'
                                                                        font_style: "H6"
                                                        MDCard:
                                                                orientation: 'vertical'
                                                                padding: "10dp"
                                                                size_hint: None, None
                                                                size: "140dp", "70dp"
                                                                md_bg_color:"00008B"
                                                                pos_hint:{"center_x":0.75,'center_y':0.68}

                                                                MDLabel:
                                                                        text: "User-Friendly"
                                                                        halign: 'center'
                                                                        font_style: "H6"

                                                        MDCard:
                                                                orientation: 'vertical'
                                                                padding: "10dp"
                                                                size_hint: None, None
                                                                size: "100dp", "70dp"
                                                                md_bg_color:"#F0E68C"
                                                                pos_hint:{"center_x":0.15,'center_y':0.5}

                                                                MDLabel:
                                                                        text: "Step 1: Sign Up"
                                                                        halign: 'center'
                                                                        font_style: "H6"
                                                                        color:"#000000"

                                                        MDCard:
                                                                orientation: 'vertical'
                                                                padding: "10dp"
                                                                size_hint: None, None
                                                                size: "120dp", "70dp"
                                                                md_bg_color:"FFFF00"
                                                                pos_hint:{"center_x":0.42,'center_y':0.5}
                                                                MDLabel:
                                                                        text: "Step 2: Choose Seat"
                                                                        halign: 'center'
                                                                        font_style: "H6"
                                                                        color:"#000000"

                                                        MDCard:
                                                                orientation: 'vertical'
                                                                padding: "10dp"
                                                                size_hint: None, None
                                                                size: "120dp", "70dp"
                                                                md_bg_color:"FFD700"
                                                                pos_hint:{"center_x":0.72,'center_y':0.5}

                                                                MDLabel:
                                                                        text: "Step 3: Confirm Booking"
                                                                        halign: 'center'
                                                                        font_style: "H6"
                                                                        color:"#000000"
                                                        MDCard:
                                                                orientation: 'horizontal'
                                                                size_hint_y: None
                                                                height: "200dp"
                                                                md_bg_color:"#800080"
                                                                #radius:[20,20,0,0]
                                                                pos_hint:{"center_x":0.52}
                                                                MDGridLayout:
                                                                        cols:3
                                                                        MDGridLayout:
                                                                                rows:4
                                                                                spacing:"10dp"
                                                                                MDLabel:
                                                                                        text: "Contact Information"
                                                                                        halign: 'left'
                                                                                        font_size:"20dp"
                                                                                        pos_hint:{'center_x':0.5}


                                                                                MDLabel:
                                                                                        text: "Address: Library Street, City"
                                                                                        halign: 'left'
                                                                                        pos_hint:{'center_x':0.5}

                                                                                MDLabel:
                                                                                        text: "Phone: 123-456-7890"
                                                                                        halign: 'left'

                                                                                MDLabel:
                                                                                        text: "Email: info@library.com"
                                                                                        halign: 'left'
                                                                        MDGridLayout:
                                                                                rows:2
                                                                                spacing:"10dp"
                                                                                MDLabel:
                                                                                        text: "Social Media"
                                                                                        halign: 'left'

                                                                                MDLabel:
                                                                                        text: "[Icons for Social Media Links]"
                                                                                        halign: 'left'
                                                                        MDGridLayout:
                                                                                rows:3
                                                                                spacing:"10dp"
                                                                                MDLabel:
                                                                                        text: "Useful Links"
                                                                                        halign: 'left'

                                                                                MDLabel:
                                                                                        text: "Privacy Policy"
                                                                                        halign: 'left'

                                                                                MDLabel:
                                                                                        text: "Terms of Service"
                                                                                        halign: 'left'



                        MDNavigationDrawer:
                                id:nav_drawer
                                radius:(0,16,16,0)
                                MDNavigationDrawerMenu:
                                        DrawerClickableItem:
                                                text:"Login"
                                                on_press:
                                                        nav_drawer.set_state('close')
                                                        app.root.current = 'login'





<Login_scr>:
        name:"login"
        on_enter:app.connect_to_firebase()
        Image:
                source:"liph.png"
                allow_stretch:True
                keep_ratio:False
        MDFloatLayout:
                MDTopAppBar:
                        title: "STUDENT LOGIN"
                        left_action_items: [["arrow-left", lambda x: app.switch_to_home()]]
                        pos_hint:{'center_y':.95}
                        elevation: 10
                MDLabel:
                        text:"WELCOME"
                        color:"#008080"
                        halign:"center"
                        pos_hint:{'center_y':0.8}
                        font_size:"48dp"
                MDTextField:
                        id:username
                        hint_text:"Username/Enrollment"
                        text_color:"Amber"
                        helper_text:"expample@tmu.ac.in"
                        helper_text_mode:"on_focus"
                        icon_right:"account"
                        helper_text_size:20
                        icon_right_color:"#FFA500"
                        pos_hint:{'center_x':0.5,'center_y':0.654}
                        size_hint_x:None
                        width:400
                        font_size:"25dp"
                        line_color_normal:"#FFFF00"
                        line_color_focus:"#FFA500"
                        multiline:False
                        mode:"rectangle"
                        on_text:self.text = self.text.replace(" ","")
                        write_tab:False


                MDTextField:
                        id:passwd
                        hint_text:"Password"
                        helper_text_mode:"on_focus"
                        icon_right:"eye-off"
                        password:True
                        pos_hint:{'center_x':0.5,'center_y':0.5}
                        size_hint_x:None
                        width:400
                        font_size:"25dp"
                        line_color_normal:"#FFFF00"
                        line_color_focus:"#FFA500"
                        mode:"rectangle"
                        multiline:False
                        on_text:self.text = self.text.replace(" ","")
                        write_tab:False

                MDFloatLayout:
                        spacing:"5dp"
                        MDCheckbox:
                                id:cb
                                size_hint:None, None
                                width:"30dp"
                                height:"30dp"
                                pos_hint:{'center_x':0.3,'center_y':0.4}
                                on_press:
                                        passwd.password=False if passwd.password == True else True
                                        passwd.icon_right = "eye" if passwd.icon_right == "eye-off" else "eye-off"

                        MDLabel:
                                text: "[ref=Show Password]Show Password[/ref]"
                                markup:True
                                halign:"center"
                                pos_hint:{'center_x':0.5,'center_y':0.4}
                                font_color:"#FFA500"
                                on_ref_press:
                                        cb.active =False if cb.active==True else True
                                        passwd.password=False if passwd.password == True else True
                                        passwd.icon_right = "eye" if passwd.icon_right == "eye-off" else "eye-off"

                MDRectangleFlatButton:
                        text : "SIGN IN"
                        pos_hint:{'center_x':0.5,'center_y':0.3}
                        md_bg_color:"#A52A2A"
                        font_size:"22dp"
                        on_press:app.get_data()

<User_Dashboard>:
        name:"user_dashboard"
        id:user_dashboard
        Image:
            #C://Users//asus//Documents//appsdevlopment using python//
                source:"liph.png"
                allow_stretch:True
                keep_ratio:False
        MDScreen:
                MDNavigationLayout:
                        MDScreenManager:
                                MDScreen:
                                        BoxLayout:
                                                orientation: 'vertical'
                                                MDTopAppBar:
                                                        title: "Library Seat Booking System"
                                                        md_bg_color:"D2B48C"
                                                        left_action_items: [["menu", lambda x: nav_drawer1.set_state("open")]]
                                                        right_action_items: [["logout", lambda x: app.logout()]]
                                                MDBoxLayout:
                                                        orientation: 'vertical'
                                                        padding: "10dp"
                                                        spacing: "10dp"
                                                        MDLabel:
                                                                id:name
                                                                halign: 'center'
                                                                font_style: "H4"
                                                        MDBoxLayout:
                                                                orientation: 'horizontal'
                                                                spacing: "10dp"
                                                                MDBoxLayout:
                                                                        orientation: 'vertical'
                                                                        padding: "10dp"
                                                                        md_bg_color: "D2B48C"
                                                                        radius: [10,10,10,10]
                                                                        MDLabel:
                                                                                text: "Upcoming Bookings"
                                                                                halign: 'center'
                                                                                font_style: "H6"
                                                                        MDRaisedButton:
                                                                                text: "Upcoming Bookings"
                                                                                spacing:"5dp"
                                                                                pos_hint: {'center_x': 0.5}
                                                                                on_press:app.upcoming_booking()

                                                                MDBoxLayout:
                                                                        orientation: 'vertical'
                                                                        padding: "10dp"
                                                                        md_bg_color: "D2B48C"
                                                                        radius: [10,10,10,10]
                                                                        MDLabel:
                                                                                text: "Past Bookings"
                                                                                halign: 'center'
                                                                                font_style: "H6"
                                                                        MDRaisedButton:
                                                                                text: "Past Bookings"
                                                                                spacing:"5dp"
                                                                                pos_hint: {'center_x': 0.5}
                                                                                on_press:app.past_booking()
                                                        MDBoxLayout:
                                                                orientation: 'vertical'
                                                                padding: "10dp"
                                                                spacing: "10dp"
                                                                md_bg_color: "D2B48C"
                                                                radius: [10,10,10,10]
                                                                MDLabel:
                                                                        text: "Book a Seat"
                                                                        halign: 'center'
                                                                        font_style: "H6"
                                                                MDRaisedButton:
                                                                        text: "Book Seat"
                                                                        spacing:"5dp"
                                                                        pos_hint: {'center_x': 0.5}
                                                                        on_press:app.book_seat()

                                                        MDBoxLayout:
                                                                orientation: 'horizontal'
                                                                spacing: "10dp"
                                                                MDBoxLayout:
                                                                        orientation: 'vertical'
                                                                        padding: "10dp"
                                                                        md_bg_color: "D2B48C"
                                                                        radius: [10,10,10,10]
                                                                        MDLabel:
                                                                                text: "Change User Password"
                                                                                halign: 'center'
                                                                                spacing:"5dp"
                                                                                font_style: "H6"
                                                                        MDRaisedButton:
                                                                                text: "Change Password"
                                                                                spacing:"5dp"
                                                                                pos_hint: {'center_x': 0.5}
                                                                                on_press:app.switch_to_Account_setting()
                                                                MDBoxLayout:
                                                                        orientation: 'vertical'
                                                                        padding: "10dp"
                                                                        md_bg_color: "D2B48C"
                                                                        radius: [10,10,10,10]
                                                                        MDLabel:
                                                                                text: "Account Details"
                                                                                halign: 'center'
                                                                                spacing:"5dp"
                                                                                font_style: "H6"
                                                                        MDLabel:
                                                                                id:name1
                                                                                spacing:"5dp"
                                                                                halign: 'center'
                                                                        MDRaisedButton:
                                                                                text: "Change Photo"
                                                                                spacing:"5dp"
                                                                                pos_hint: {'center_x': 0.5}
                                                                                on_press:app.hello_print()

                                                        MDBoxLayout:
                                                                orientation: 'vertical'
                                                                padding: "10dp"
                                                                spacing: "10dp"
                                                                md_bg_color: "D2B48C"
                                                                radius: [10, 10, 10, 10]
                                                                MDLabel:
                                                                        text: "Support"
                                                                        halign: 'center'
                                                                        font_style: "H6"
                                                                MDLabel:
                                                                        text: "Contact Information"
                                                                        halign: 'center'
                                                                MDRaisedButton:
                                                                        text: "Contact Support"
                                                                        spacing:"5dp"
                                                                        pos_hint: {'center_x': 0.5}
                                                                        on_press:app.switch_to_help()

                        MDNavigationDrawer:
                                id: nav_drawer1
                                radius: (0, 16, 16, 0)
                                MDNavigationDrawerMenu:
                                        MDNavigationDrawerHeader:
                                                BoxLayout:
                                                        orientation: "horizontal"  # Set to horizontal for image and text side by side
                                                        size_hint: None, None
                                                        size: "280dp", "200dp"
                                                        padding: "10dp"
                                                        spacing: "10dp"  # Space between the image and text

                                                        # Image element
                                                        Image:
                                                                id: header_image
                                                                source: "default_user.png"  # Default image
                                                                size_hint: None, None
                                                                size: "100dp", "100dp"
                                                                pos_hint: {"center_y": 0.5}



                                                        # User info (Image and Text side by side)
                                                        BoxLayout:
                                                                orientation: "vertical"
                                                                size_hint: None, None
                                                                padding: "5dp"
                                                                MDLabel:
                                                                        id: header_title
                                                                        text: "User Name"
                                                                        color: "00FFFF"
                                                                        size_hint_x:None
                                                                        width:"200dp"
                                                                        halign: "left"
                                                                        font_size: "20dp"
                                        DrawerClickableItem:
                                                text:"Home"
                                                on_press:
                                                        nav_drawer1.set_state('close')
                                                        app.root.current = 'user_dashboard'
                                        DrawerClickableItem:
                                                text:"Upcoming Booking"
                                                on_press:
                                                        nav_drawer1.set_state('close')
                                                        app.upcoming_booking()
                                        DrawerClickableItem:
                                                text:"Past Booking"
                                                on_press:
                                                        nav_drawer1.set_state('close')
                                                        app.past_booking()
                                        DrawerClickableItem:
                                                text:"Book a Seat"
                                                on_press:
                                                        nav_drawer1.set_state('close')
                                                        app.book_seat()
                                        DrawerClickableItem:
                                                text:"Account Settings"
                                                on_press:
                                                        nav_drawer1.set_state('close')
                                                        app.root.current = "account_setting"
                                        DrawerClickableItem:
                                                text:"Help"
                                                on_press:
                                                        nav_drawer1.set_state('close')
                                                        app.switch_to_help()
                                        DrawerClickableItem:
                                                text:"Logout"
                                                on_press:
                                                        nav_drawer1.set_state('close')
                                                        app.root.current = "home"




<Upcoming_Booking>:
        name:"upcoming_booking"
        Image:
                source:"liph.png"
                allow_stretch:True
                keep_ratio:False
        MDFloatLayout:
                MDTopAppBar:
                        title: "Library Seat Booking System"
                        pos_hint:{'center_y':0.95}
                        md_bg_color:"D2B48C"
                        left_action_items: [["arrow-left", lambda x: app.switch_to_user_dashboard()]]
                MDLabel:
                        text:"Upcoming Booking"
                        #halign:"left"
                        font_size:"25dp"
                        pos_hint:{'center_y':0.88}
                        color:"#FF00FF"
                MDScrollView:
                        pos_hint:{"center_x":0.5,"center_y":0.45}
                        size_hint: 0.9, 0.8
                        bar_color: 0, 0, 0, 1
                        bar_inactive_color: 0, 0, 0, 0.5
                        MDList:
                                id:upcoming_booking


<Past_booking>:
        name:"past_booking"
        Image:
                source:"liph.png"
                allow_stretch:True
                keep_ratio:False
        MDFloatLayout:
                MDTopAppBar:
                        title: "Library Seat Booking System"
                        pos_hint:{'center_y':0.95}
                        md_bg_color:"D2B48C"
                        left_action_items: [["arrow-left", lambda x: app.switch_to_user_dashboard()]]
                MDLabel:
                        text:"Past Booking"
                        halign:"left"
                        font_size:"25dp"
                        pos_hint:{'center_y':0.88}
                        color:"#FF00FF"
                MDScrollView:
                        pos_hint:{"center_x":0.5,"center_y":0.45}
                        size_hint: 0.9, 0.8
                        bar_color: 0, 0, 0, 1
                        bar_inactive_color: 0, 0, 0, 0.5
                        MDList:
                                id:past_booking


<Account_setting>:
        name:"account_setting"
        Image:
            #C://Users//asus//Documents//appsdevlopment using python//
                source:"liph.png"
                allow_stretch:True
                keep_ratio:False
        BoxLayout:
                orientation: 'vertical'
                MDTopAppBar:
                        title: "Library Seat Booking System"
                        md_bg_color:"D2B48C"
                        left_action_items: [["arrow-left", lambda x: app.switch_to_user_dashboard()]]
                MDFloatLayout:
                        MDLabel:
                                text:"Change Password"
                                font_size:"45dp"
                                color:"#008080"
                                halign:"center"
                                pos_hint:{"center_y":0.95}
                        MDTextField:
                                id:old_passwd
                                hint_text:"Old Password"
                                helper_text_mode:"on_focus"
                                icon_right:"eye-off"
                                password:True
                                pos_hint:{'center_x':0.5,'center_y':0.82}
                                size_hint_x:None
                                width:500
                                font_size:"25dp"
                                line_color_normal:"#FFFF00"
                                line_color_focus:"#FFA500"
                                mode:"rectangle"
                                multiline:False
                                on_text:self.text = self.text.replace(" ","")
                                write_tab:False
                        MDFloatLayout:
                                MDCheckbox:
                                        id:cb
                                        size_hint:None, None
                                        width:"30dp"
                                        height:"30dp"
                                        pos_hint:{'center_x':0.3,'center_y':0.73}
                                        on_press:
                                                old_passwd.password=False if old_passwd.password == True else True
                                                old_passwd.icon_right = "eye" if old_passwd.icon_right == "eye-off" else "eye-off"

                                MDLabel:
                                        text: "[ref=Show Password]Show Password[/ref]"
                                        markup:True
                                        halign:"center"
                                        pos_hint:{'center_x':0.5,'center_y':0.73}
                                        font_color:"#FFA500"
                                        on_ref_press:
                                                cb.active =False if cb.active==True else True
                                                old_passwd.password=False if old_passwd.password == True else True
                                                old_passwd.icon_right = "eye" if old_passwd.icon_right == "eye-off" else "eye-off"
                        MDTextField:
                                id:new_passwd
                                hint_text:"New Password"
                                helper_text_mode:"on_focus"
                                icon_right:"eye-off"
                                password:True
                                pos_hint:{'center_x':0.5,'center_y':0.65}
                                size_hint_x:None
                                width:500
                                font_size:"25dp"
                                line_color_normal:"#FFFF00"
                                line_color_focus:"#FFA500"
                                mode:"rectangle"
                                multiline:False
                                on_text:self.text = self.text.replace(" ","")
                                write_tab:False
                        MDFloatLayout:
                                MDCheckbox:
                                        id:cb1
                                        size_hint:None, None
                                        width:"30dp"
                                        height:"30dp"
                                        pos_hint:{'center_x':0.3,'center_y':0.56}
                                        on_press:
                                                new_passwd.password=False if new_passwd.password == True else True
                                                new_passwd.icon_right = "eye" if new_passwd.icon_right == "eye-off" else "eye-off"

                                MDLabel:
                                        text: "[ref=Show Password]Show Password[/ref]"
                                        markup:True
                                        halign:"center"
                                        pos_hint:{'center_x':0.5,'center_y':0.56}
                                        font_color:"#FFA500"
                                        on_ref_press:
                                                cb1.active =False if cb1.active==True else True
                                                new_passwd.password=False if new_passwd.password == True else True
                                                new_passwd.icon_right = "eye" if new_passwd.icon_right == "eye-off" else "eye-off"
                        MDTextField:
                                id:con_passwd
                                hint_text:"Confirm-Password"
                                helper_text_mode:"on_focus"
                                icon_right:"eye-off"
                                password:True
                                pos_hint:{'center_x':0.5,'center_y':0.48}
                                size_hint_x:None
                                width:500
                                font_size:"25dp"
                                line_color_normal:"#FFFF00"
                                line_color_focus:"#FFA500"
                                mode:"rectangle"
                                multiline:False
                                on_text:self.text = self.text.replace(" ","")
                                write_tab:False
                        MDFloatLayout:
                                MDCheckbox:
                                        id:cb2
                                        size_hint:None, None
                                        width:"30dp"
                                        height:"30dp"
                                        pos_hint:{'center_x':0.3,'center_y':0.38}
                                        on_press:
                                                con_passwd.password=False if con_passwd.password == True else True
                                                con_passwd.icon_right = "eye" if con_passwd.icon_right == "eye-off" else "eye-off"

                                MDLabel:
                                        text: "[ref=Show Password]Show Password[/ref]"
                                        markup:True
                                        halign:"center"
                                        pos_hint:{'center_x':0.5,'center_y':0.38}
                                        font_color:"#FFA500"
                                        on_ref_press:
                                                cb2.active =False if cb2.active==True else True
                                                con_passwd.password=False if con_passwd.password == True else True
                                                con_passwd.icon_right = "eye" if con_passwd.icon_right == "eye-off" else "eye-off"

                        MDRectangleFlatButton:
                                text : "CHANGE PASSWORD"
                                pos_hint:{'center_x':0.5,'center_y':0.28}
                                md_bg_color:"#A52A2A"
                                font_size:"22dp"
                                on_press:app.check_and_update()

<Help>:
        name:"help"
        on_pre_enter:app.on_pre_enter_on_help()
        Image:
            #C://Users//asus//Documents//appsdevlopment using python//
                source:"liph.png"
                allow_stretch:True
                keep_ratio:False
        MDFloatLayout:
                MDTopAppBar:
                        title:"Help & Support Assistance"
                        title_size:"45dp"
                        md_bg_color:"D2B48C"
                        pos_hint:{'center_y':0.95}
                        left_action_items: [["arrow-left", lambda x: app.switch_to_user_dashboard()]]
                        elevation:3
                MDLabel:
                        text: "Select a question:"
                        halign: "left"
                        pos_hint:{"center_x":0.53,"center_y":0.88}
                MDFloatLayout:
                        id:help_questions

                BoxLayout:
                        size_hint: 1, None
                        height:dp(230)
                        padding: dp(10)
                        pos_hint:{'center_y':0.3}
                        MDScrollView:
                                id: scroll_view
                                do_scroll_x: False
                                do_scroll_y: True
                                on_scroll_y: app.update_scroll_status(self.scroll_y)
                                MDBoxLayout:
                                        orientation: "vertical"
                                        size_hint_y: None
                                        height: self.minimum_height
                                        spacing: dp(10)
                                        MDCard:
                                                id: messages_box
                                                orientation: 'vertical'
                                                adaptive_height: True
                                                padding: "10dp"
                                                spacing: "10dp"
                                                md_bg_color: 1, 1, 1, 0
                                                #size_hint_y:"100dp"
                                                                            
                MDTextField:
                        id: support_field
                        hint_text: "Write your question here..."
                        size_hint: None, None
                        size: dp(300), dp(100)
                        pos_hint: {"center_x": 0.35, "center_y": 0.05}
                        multiline: True
                        visible: False
                        opacity: 0
                        font_size:"25dp"
                        line_color_normal:"#FFFF00"
                        line_color_focus:"#FFA500"
                        write_tab:False
                MDRectangleFlatButton:
                        id:support_button
                        text : "SEND"
                        pos_hint:{'center_x':0.8,'center_y':0.05}
                        md_bg_color:"#A52A2A"
                        font_size:"22dp"
                        opacity: 0
                        on_press:app.handle_contact_support()


<Payment_scr>:
        name:"payment"
        Image:
            #C://Users//asus//Documents//appsdevlopment using python//
                source:"liph.png"
                allow_stretch:True
                keep_ratio:False
        MDBoxLayout:
                orientation:"vertical"
                MDTopAppBar:
                        title:"Payment"
                        md_bg_color:"D2B48C"
                        #left_action_items: [["arrow-left", lambda x: pass]]
                        elevation:3


<Hall_selection>:
        name:"hall_selection"
        on_enter:app.on_enter_on_hall()
        Image:
            #C://Users//asus//Documents//appsdevlopment using python//
                source:"liph.png"
                allow_stretch:True
                keep_ratio:False
        MDBoxLayout:
                orientation:"vertical"
                MDTopAppBar:
                        title:"Number of Halls"
                        md_bg_color:"D2B48C"
                        left_action_items: [["arrow-left", lambda x: app.switch_to_user_dashboard()]]
                        elevation:3

                MDScrollView:
                        pos_hint:{"center_x":0.55,"center_y":0.3}
                        MDList:
                                id:container


<Seat_selection1>:
        name:"seat_selection1"
        on_enter:app.on_pre_enter_on_seat_selection1()
        Image:
            #C://Users//asus//Documents//appsdevlopment using python//
                source:"liph.png"
                allow_stretch:True
                keep_ratio:False
        MDFloatLayout:
                MDTopAppBar:
                        title:"Please Select Seat To Book"
                        title_size:"45dp"
                        md_bg_color:"D2B48C"
                        pos_hint:{'center_y':0.95}
                        left_action_items: [["arrow-left", lambda x: app.switch_to_hall_selection()]]
                        elevation:3
                MDLabel:
                        text:"Please Select Seat To Book"
                        color:"#008080"
                        halign:"center"
                        pos_hint:{"center_y":0.8}
                        font_size:"45dp"
                        #pos_hint:{"center_x":0.1,"center_y":0.7}
                MDFloatLayout:
                        #first row
                        MDIconButton:
                                id:seat1
                                name:"A1"
                                icon: "seat"
                                pos_hint:{"center_x":0.1,"center_y":0.7}
                                on_release:app.check_seat_availability1("A1")
                        MDIconButton:
                                id:seat2
                                name:"A2"
                                icon: "seat"
                                pos_hint:{"center_x":0.17,"center_y":0.7}
                                on_release:app.check_seat_availability1("A2")
                        MDIconButton:
                                id:seat3
                                name:"A3"
                                icon: "seat"
                                pos_hint:{"center_x":0.24,"center_y":0.7}
                                on_release:app.check_seat_availability1("A3")
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.1,"center_y":0.67}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.17,"center_y":0.67}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.24,"center_y":0.67}
                        MDIconButton:
                                id:seat7
                                name:"A7"
                                icon: "seat"
                                pos_hint:{"center_x":0.1,"center_y":0.65}
                                on_release:app.check_seat_availability1("A7")
                        MDIconButton:
                                id:seat8
                                name:"A8"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A8")
                                pos_hint:{"center_x":0.17,"center_y":0.65}
                        MDIconButton:
                                id:seat9
                                name:"A9"
                                icon: "seat"
                                pos_hint:{"center_x":0.24,"center_y":0.65}
                                on_release:app.check_seat_availability1("A9")
                        MDIconButton:
                                id:seat4
                                name:"A4"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A4")
                                pos_hint:{"center_x":0.6,"center_y":0.7}
                        MDIconButton:
                                id:seat5
                                name:"A5"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A5")
                                pos_hint:{"center_x":0.67,"center_y":0.7}
                        MDIconButton:
                                id:seat6
                                name:"A6"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A6")
                                pos_hint:{"center_x":0.74,"center_y":0.7}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.6,"center_y":0.67}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.67,"center_y":0.67}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.74,"center_y":0.67}
                        MDIconButton:
                                icon:'window-closed'
                                icon_size:"48dp"
                                disabled:True
                                disabled_color:"#FFFFFF"
                                pos_hint:{"center_x":0.8,"center_y":0.67}
                        MDIconButton:
                                id:seat10
                                name:"A10"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A10")
                                pos_hint:{"center_x":0.6,"center_y":0.65}
                        MDIconButton:
                                id:seat11
                                name:"A11"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A11")
                                pos_hint:{"center_x":0.67,"center_y":0.65}
                        MDIconButton:
                                id:seat12
                                name:"A12"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A12")
                                pos_hint:{"center_x":0.74,"center_y":0.65}

                        #second row
                        MDIconButton:
                                id:seat13
                                name:"A13"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A13")
                                pos_hint:{"center_x":0.1,"center_y":0.6}
                        MDIconButton:
                                id:seat14
                                name:"A14"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A14")
                                pos_hint:{"center_x":0.17,"center_y":0.6}
                        MDIconButton:
                                id:seat15
                                name:"A15"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A15")
                                pos_hint:{"center_x":0.24,"center_y":0.6}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.1,"center_y":0.57}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.17,"center_y":0.57}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.24,"center_y":0.57}
                        MDIconButton:
                                id:seat19
                                name:"A19"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A19")
                                pos_hint:{"center_x":0.1,"center_y":0.55}
                        MDIconButton:
                                id:seat20
                                name:"A20"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A20")
                                pos_hint:{"center_x":0.17,"center_y":0.55}
                        MDIconButton:
                                id:seat21
                                name:"A21"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A21")
                                pos_hint:{"center_x":0.24,"center_y":0.55}
                        MDIconButton:
                                id:seat16
                                name:"A16"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A16")
                                pos_hint:{"center_x":0.6,"center_y":0.6}
                        MDIconButton:
                                id:seat17
                                name:"A17"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A17")
                                pos_hint:{"center_x":0.67,"center_y":0.6}
                        MDIconButton:
                                id:seat18
                                name:"A18"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A18")
                                pos_hint:{"center_x":0.74,"center_y":0.6}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.6,"center_y":0.57}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.67,"center_y":0.57}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.74,"center_y":0.57}

                        MDIconButton:
                                id:seat22
                                name:"A22"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A22")
                                pos_hint:{"center_x":0.6,"center_y":0.55}
                        MDIconButton:
                                id:seat23
                                name:"A23"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A23")
                                pos_hint:{"center_x":0.67,"center_y":0.55}
                        MDIconButton:
                                id:seat24
                                name:"A24"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A24")
                                pos_hint:{"center_x":0.74,"center_y":0.55}
                        #third row
                        MDIconButton:
                                id:seat25
                                name:"A25"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A25")
                                pos_hint:{"center_x":0.1,"center_y":0.5}
                        MDIconButton:
                                id:seat26
                                name:"A26"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A26")
                                pos_hint:{"center_x":0.17,"center_y":0.5}
                        MDIconButton:
                                id:seat27
                                name:"A27"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A27")
                                pos_hint:{"center_x":0.24,"center_y":0.5}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.1,"center_y":0.47}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.17,"center_y":0.47}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.24,"center_y":0.47}
                        MDIconButton:
                                id:seat31
                                name:"A31"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A31")
                                pos_hint:{"center_x":0.1,"center_y":0.45}
                        MDIconButton:
                                id:seat32
                                name:"A32"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A32")
                                pos_hint:{"center_x":0.174,"center_y":0.45}
                        MDIconButton:
                                id:seat33
                                name:"A32"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A33")
                                pos_hint:{"center_x":0.24,"center_y":0.45}
                        MDIconButton:
                                id:seat28
                                name:"A28"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A28")
                                pos_hint:{"center_x":0.6,"center_y":0.5}
                        MDIconButton:
                                id:seat29
                                name:"A29"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A29")
                                pos_hint:{"center_x":0.67,"center_y":0.5}
                        MDIconButton:
                                id:seat30
                                name:"A30"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A30")
                                pos_hint:{"center_x":0.74,"center_y":0.5}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.6,"center_y":0.47}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.67,"center_y":0.47}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.74,"center_y":0.47}

                        MDIconButton:
                                id:seat34
                                name:"A34"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A34")
                                pos_hint:{"center_x":0.6,"center_y":0.45}
                        MDIconButton:
                                id:seat35
                                name:"A35"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A35")
                                pos_hint:{"center_x":0.67,"center_y":0.45}
                        MDIconButton:
                                id:seat36
                                name:"A36"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A36")
                                pos_hint:{"center_x":0.74,"center_y":0.45}
                        #fourth row
                        MDIconButton:
                                id:seat37
                                name:"A37"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A37")
                                pos_hint:{"center_x":0.1,"center_y":0.4}
                        MDIconButton:
                                id:seat38
                                name:"A38"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A38")
                                pos_hint:{"center_x":0.17,"center_y":0.4}
                        MDIconButton:
                                id:seat39
                                name:"A39"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A39")
                                pos_hint:{"center_x":0.24,"center_y":0.4}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.1,"center_y":0.37}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.17,"center_y":0.37}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.24,"center_y":0.37}
                        MDIconButton:
                                id:seat43
                                name:"A43"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A43")
                                pos_hint:{"center_x":0.1,"center_y":0.35}
                        MDIconButton:
                                id:seat44
                                name:"A44"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A44")
                                pos_hint:{"center_x":0.17,"center_y":0.35}
                        MDIconButton:
                                id:seat45
                                name:"A45"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A45")
                                pos_hint:{"center_x":0.24,"center_y":0.35}
                        MDIconButton:
                                id:seat40
                                name:"A40"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A40")
                                pos_hint:{"center_x":0.6,"center_y":0.4}
                        MDIconButton:
                                id:seat41
                                name:"A41"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A41")
                                pos_hint:{"center_x":0.67,"center_y":0.4}
                        MDIconButton:
                                id:seat42
                                name:"A42"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A42")
                                pos_hint:{"center_x":0.74,"center_y":0.4}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.6,"center_y":0.37}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.67,"center_y":0.37}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.74,"center_y":0.37}

                        MDIconButton:
                                id:seat46
                                name:"A46"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A46")
                                pos_hint:{"center_x":0.6,"center_y":0.35}
                        MDIconButton:
                                id:seat47
                                name:"A47"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A47")
                                pos_hint:{"center_x":0.67,"center_y":0.35}
                        MDIconButton:
                                id:seat48
                                name:"A48"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A48")
                                pos_hint:{"center_x":0.74,"center_y":0.35}
                        #fifth row
                        MDIconButton:
                                id:seat49
                                name:"A49"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A49")
                                pos_hint:{"center_x":0.1,"center_y":0.3}
                        MDIconButton:
                                id:seat50
                                name:"A50"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A50")
                                pos_hint:{"center_x":0.17,"center_y":0.3}
                        MDIconButton:
                                id:seat51
                                name:"A51"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A51")
                                pos_hint:{"center_x":0.24,"center_y":0.3}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.1,"center_y":0.27}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.17,"center_y":0.27}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.24,"center_y":0.27}
                        MDIconButton:
                                id:seat55
                                name:"A55"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A55")
                                pos_hint:{"center_x":0.1,"center_y":0.25}
                        MDIconButton:
                                id:seat56
                                name:"A56"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A56")
                                pos_hint:{"center_x":0.17,"center_y":0.25}
                        MDIconButton:
                                id:seat57
                                name:"A57"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A57")
                                pos_hint:{"center_x":0.24,"center_y":0.25}
                        MDIconButton:
                                id:seat52
                                name:"A52"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A52")
                                pos_hint:{"center_x":0.6,"center_y":0.3}
                        MDIconButton:
                                id:seat53
                                name:"A53"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A53")
                                pos_hint:{"center_x":0.67,"center_y":0.3}
                        MDIconButton:
                                id:seat54
                                name:"A54"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A54")
                                pos_hint:{"center_x":0.74,"center_y":0.3}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.6,"center_y":0.27}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.67,"center_y":0.27}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.74,"center_y":0.27}

                        MDIconButton:
                                id:seat58
                                name:"A58"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A58")
                                pos_hint:{"center_x":0.6,"center_y":0.25}
                        MDIconButton:
                                id:seat59
                                name:"A59"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A59")
                                pos_hint:{"center_x":0.67,"center_y":0.25}
                        MDIconButton:
                                id:seat60
                                name:"A60"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A60")
                                pos_hint:{"center_x":0.74,"center_y":0.25}
                        #sixth row
                        MDIconButton:
                                id:seat61
                                name:"A61"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A61")
                                pos_hint:{"center_x":0.1,"center_y":0.2}
                        MDIconButton:
                                id:seat62
                                name:"A62"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A62")
                                pos_hint:{"center_x":0.17,"center_y":0.2}
                        MDIconButton:
                                id:seat63
                                name:"A63"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A63")
                                pos_hint:{"center_x":0.24,"center_y":0.2}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.1,"center_y":0.17}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.17,"center_y":0.17}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.24,"center_y":0.17}
                        MDIconButton:
                                id:seat67
                                name:"A67"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A67")
                                pos_hint:{"center_x":0.1,"center_y":0.15}
                        MDIconButton:
                                id:seat68
                                name:"A68"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A68")
                                pos_hint:{"center_x":0.174,"center_y":0.15}
                        MDIconButton:
                                id:seat69
                                name:"A69"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A69")
                                pos_hint:{"center_x":0.24,"center_y":0.15}
                        MDIconButton:
                                id:seat64
                                name:"A64"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A64")
                                pos_hint:{"center_x":0.6,"center_y":0.2}
                        MDIconButton:
                                id:seat65
                                name:"A65"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A65")
                                pos_hint:{"center_x":0.67,"center_y":0.2}
                        MDIconButton:
                                id:seat66
                                name:"A66"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A66")
                                pos_hint:{"center_x":0.74,"center_y":0.2}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.6,"center_y":0.17}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.67,"center_y":0.17}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.74,"center_y":0.17}

                        MDIconButton:
                                id:seat70
                                name:"A70"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A70")
                                pos_hint:{"center_x":0.6,"center_y":0.15}
                        MDIconButton:
                                id:seat71
                                name:"A71"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A71")
                                pos_hint:{"center_x":0.67,"center_y":0.15}
                        MDIconButton:
                                id:seat72
                                name:"A72"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A72")
                                pos_hint:{"center_x":0.74,"center_y":0.15}
                        #seventh row
                        MDIconButton:
                                id:seat73
                                name:"A73"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A73")
                                pos_hint:{"center_x":0.1,"center_y":0.1}
                        MDIconButton:
                                id:seat74
                                name:"A74"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A74")
                                pos_hint:{"center_x":0.17,"center_y":0.1}
                        MDIconButton:
                                id:seat75
                                name:"A75"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A75")
                                pos_hint:{"center_x":0.24,"center_y":0.1}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.1,"center_y":0.07}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.17,"center_y":0.07}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.24,"center_y":0.07}
                        MDIconButton:
                                id:seat79
                                name:"A79"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A79")
                                pos_hint:{"center_x":0.1,"center_y":0.05}
                        MDIconButton:
                                id:seat80
                                name:"A80"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A80")
                                pos_hint:{"center_x":0.17,"center_y":0.05}
                        MDIconButton:
                                id:seat81
                                name:"A81"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A81")
                                pos_hint:{"center_x":0.24,"center_y":0.05}
                        MDIconButton:
                                id:seat76
                                name:"A76"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A76")
                                pos_hint:{"center_x":0.6,"center_y":0.1}
                        MDIconButton:
                                id:seat77
                                name:"A77"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A77")
                                pos_hint:{"center_x":0.67,"center_y":0.1}
                        MDIconButton:
                                id:seat78
                                name:"A78"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A78")
                                pos_hint:{"center_x":0.74,"center_y":0.1}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.6,"center_y":0.07}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.67,"center_y":0.07}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.74,"center_y":0.07}

                        MDIconButton:
                                id:seat82
                                name:"A82"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A82")
                                pos_hint:{"center_x":0.6,"center_y":0.05}
                        MDIconButton:
                                id:seat83
                                name:"A83"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A83")
                                pos_hint:{"center_x":0.67,"center_y":0.05}
                        MDIconButton:
                                id:seat84
                                name:"A84"
                                icon: "seat"
                                on_release:app.check_seat_availability1("A84")
                                pos_hint:{"center_x":0.74,"center_y":0.05}

<Seat_selection2>:
        name:"seat_selection2"
        on_enter:app.on_pre_enter_on_seat_selection2()
        Image:
            #C://Users//asus//Documents//appsdevlopment using python//
                source:"liph.png"
                allow_stretch:True
                keep_ratio:False
        MDFloatLayout:
                MDTopAppBar:
                        title:"Please Select Seat To Book"
                        title_size:"45dp"
                        md_bg_color:"D2B48C"
                        pos_hint:{'center_y':0.95}
                        left_action_items: [["arrow-left", lambda x: app.switch_to_hall_selection()]]
                        elevation:3
                MDLabel:
                        text:"Please Select Seat To Book"
                        color:"#008080"
                        halign:"center"
                        pos_hint:{"center_y":0.8}
                        font_size:"45dp"
                        #pos_hint:{"center_x":0.1,"center_y":0.7}
                MDFloatLayout:
                        #first row
                        MDIconButton:
                                id:seat1
                                name:"B1"
                                icon: "seat"
                                pos_hint:{"center_x":0.1,"center_y":0.7}
                                on_release:app.check_seat_availability2("B1")
                        MDIconButton:
                                id:seat2
                                name:"B2"
                                icon: "seat"
                                pos_hint:{"center_x":0.17,"center_y":0.7}
                                on_release:app.check_seat_availability2("B2")
                        MDIconButton:
                                id:seat3
                                name:"B3"
                                icon: "seat"
                                pos_hint:{"center_x":0.24,"center_y":0.7}
                                on_release:app.check_seat_availability2("B3")
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.1,"center_y":0.67}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.17,"center_y":0.67}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.24,"center_y":0.67}
                        MDIconButton:
                                id:seat7
                                name:"B7"
                                icon: "seat"
                                pos_hint:{"center_x":0.1,"center_y":0.65}
                                on_release:app.check_seat_availability2("B7")
                        MDIconButton:
                                id:seat8
                                name:"B8"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B8")
                                pos_hint:{"center_x":0.17,"center_y":0.65}
                        MDIconButton:
                                id:seat9
                                name:"B9"
                                icon: "seat"
                                pos_hint:{"center_x":0.24,"center_y":0.65}
                                on_release:app.check_seat_availability2("B9")
                        MDIconButton:
                                id:seat4
                                name:"B4"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B4")
                                pos_hint:{"center_x":0.6,"center_y":0.7}
                        MDIconButton:
                                id:seat5
                                name:"B5"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B5")
                                pos_hint:{"center_x":0.67,"center_y":0.7}
                        MDIconButton:
                                id:seat6
                                name:"B6"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B6")
                                pos_hint:{"center_x":0.74,"center_y":0.7}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.6,"center_y":0.67}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.67,"center_y":0.67}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.74,"center_y":0.67}
                        MDIconButton:
                                icon:'window-closed'
                                icon_size:"48dp"
                                disabled:True
                                disabled_color:"#FFFFFF"
                                pos_hint:{"center_x":0.8,"center_y":0.67}
                        MDIconButton:
                                id:seat10
                                name:"B10"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B10")
                                pos_hint:{"center_x":0.6,"center_y":0.65}
                        MDIconButton:
                                id:seat11
                                name:"B11"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B11")
                                pos_hint:{"center_x":0.67,"center_y":0.65}
                        MDIconButton:
                                id:seat12
                                name:"B12"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B12")
                                pos_hint:{"center_x":0.74,"center_y":0.65}

                        #second row
                        MDIconButton:
                                id:seat13
                                name:"B13"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B13")
                                pos_hint:{"center_x":0.1,"center_y":0.6}
                        MDIconButton:
                                id:seat14
                                name:"B14"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B14")
                                pos_hint:{"center_x":0.17,"center_y":0.6}
                        MDIconButton:
                                id:seat15
                                name:"B15"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B15")
                                pos_hint:{"center_x":0.24,"center_y":0.6}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.1,"center_y":0.57}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.17,"center_y":0.57}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.24,"center_y":0.57}
                        MDIconButton:
                                id:seat19
                                name:"B19"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B19")
                                pos_hint:{"center_x":0.1,"center_y":0.55}
                        MDIconButton:
                                id:seat20
                                name:"B20"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B20")
                                pos_hint:{"center_x":0.17,"center_y":0.55}
                        MDIconButton:
                                id:seat21
                                name:"B21"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B21")
                                pos_hint:{"center_x":0.24,"center_y":0.55}
                        MDIconButton:
                                id:seat16
                                name:"B16"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B16")
                                pos_hint:{"center_x":0.6,"center_y":0.6}
                        MDIconButton:
                                id:seat17
                                name:"B17"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B17")
                                pos_hint:{"center_x":0.67,"center_y":0.6}
                        MDIconButton:
                                id:seat18
                                name:"B18"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B18")
                                pos_hint:{"center_x":0.74,"center_y":0.6}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.6,"center_y":0.57}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.67,"center_y":0.57}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.74,"center_y":0.57}

                        MDIconButton:
                                id:seat22
                                name:"B22"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B22")
                                pos_hint:{"center_x":0.6,"center_y":0.55}
                        MDIconButton:
                                id:seat23
                                name:"B23"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B23")
                                pos_hint:{"center_x":0.67,"center_y":0.55}
                        MDIconButton:
                                id:seat24
                                name:"B24"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B24")
                                pos_hint:{"center_x":0.74,"center_y":0.55}
                        #third row
                        MDIconButton:
                                id:seat25
                                name:"B25"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B25")
                                pos_hint:{"center_x":0.1,"center_y":0.5}
                        MDIconButton:
                                id:seat26
                                name:"B26"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B26")
                                pos_hint:{"center_x":0.17,"center_y":0.5}
                        MDIconButton:
                                id:seat27
                                name:"B27"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B27")
                                pos_hint:{"center_x":0.24,"center_y":0.5}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.1,"center_y":0.47}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.17,"center_y":0.47}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.24,"center_y":0.47}
                        MDIconButton:
                                id:seat31
                                name:"B31"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B31")
                                pos_hint:{"center_x":0.1,"center_y":0.45}
                        MDIconButton:
                                id:seat32
                                name:"B32"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B32")
                                pos_hint:{"center_x":0.174,"center_y":0.45}
                        MDIconButton:
                                id:seat33
                                name:"B32"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B33")
                                pos_hint:{"center_x":0.24,"center_y":0.45}
                        MDIconButton:
                                id:seat28
                                name:"B28"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B28")
                                pos_hint:{"center_x":0.6,"center_y":0.5}
                        MDIconButton:
                                id:seat29
                                name:"B29"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B29")
                                pos_hint:{"center_x":0.67,"center_y":0.5}
                        MDIconButton:
                                id:seat30
                                name:"B30"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B30")
                                pos_hint:{"center_x":0.74,"center_y":0.5}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.6,"center_y":0.47}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.67,"center_y":0.47}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.74,"center_y":0.47}

                        MDIconButton:
                                id:seat34
                                name:"B34"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B34")
                                pos_hint:{"center_x":0.6,"center_y":0.45}
                        MDIconButton:
                                id:seat35
                                name:"B35"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B35")
                                pos_hint:{"center_x":0.67,"center_y":0.45}
                        MDIconButton:
                                id:seat36
                                name:"B36"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B36")
                                pos_hint:{"center_x":0.74,"center_y":0.45}
                        #fourth row
                        MDIconButton:
                                id:seat37
                                name:"B37"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B37")
                                pos_hint:{"center_x":0.1,"center_y":0.4}
                        MDIconButton:
                                id:seat38
                                name:"B38"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B38")
                                pos_hint:{"center_x":0.17,"center_y":0.4}
                        MDIconButton:
                                id:seat39
                                name:"B39"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B39")
                                pos_hint:{"center_x":0.24,"center_y":0.4}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.1,"center_y":0.37}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.17,"center_y":0.37}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.24,"center_y":0.37}
                        MDIconButton:
                                id:seat43
                                name:"B43"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B43")
                                pos_hint:{"center_x":0.1,"center_y":0.35}
                        MDIconButton:
                                id:seat44
                                name:"B44"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B44")
                                pos_hint:{"center_x":0.17,"center_y":0.35}
                        MDIconButton:
                                id:seat45
                                name:"B45"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B45")
                                pos_hint:{"center_x":0.24,"center_y":0.35}
                        MDIconButton:
                                id:seat40
                                name:"B40"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B40")
                                pos_hint:{"center_x":0.6,"center_y":0.4}
                        MDIconButton:
                                id:seat41
                                name:"B41"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B41")
                                pos_hint:{"center_x":0.67,"center_y":0.4}
                        MDIconButton:
                                id:seat42
                                name:"B42"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B42")
                                pos_hint:{"center_x":0.74,"center_y":0.4}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.6,"center_y":0.37}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.67,"center_y":0.37}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.74,"center_y":0.37}

                        MDIconButton:
                                id:seat46
                                name:"B46"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B46")
                                pos_hint:{"center_x":0.6,"center_y":0.35}
                        MDIconButton:
                                id:seat47
                                name:"B47"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B47")
                                pos_hint:{"center_x":0.67,"center_y":0.35}
                        MDIconButton:
                                id:seat48
                                name:"B48"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B48")
                                pos_hint:{"center_x":0.74,"center_y":0.35}
                        #fifth row
                        MDIconButton:
                                id:seat49
                                name:"B49"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B49")
                                pos_hint:{"center_x":0.1,"center_y":0.3}
                        MDIconButton:
                                id:seat50
                                name:"B50"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B50")
                                pos_hint:{"center_x":0.17,"center_y":0.3}
                        MDIconButton:
                                id:seat51
                                name:"B51"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B51")
                                pos_hint:{"center_x":0.24,"center_y":0.3}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.1,"center_y":0.27}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.17,"center_y":0.27}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.24,"center_y":0.27}
                        MDIconButton:
                                id:seat55
                                name:"B55"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B55")
                                pos_hint:{"center_x":0.1,"center_y":0.25}
                        MDIconButton:
                                id:seat56
                                name:"B56"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B56")
                                pos_hint:{"center_x":0.17,"center_y":0.25}
                        MDIconButton:
                                id:seat57
                                name:"B57"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B57")
                                pos_hint:{"center_x":0.24,"center_y":0.25}
                        MDIconButton:
                                id:seat52
                                name:"B52"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B52")
                                pos_hint:{"center_x":0.6,"center_y":0.3}
                        MDIconButton:
                                id:seat53
                                name:"B53"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B53")
                                pos_hint:{"center_x":0.67,"center_y":0.3}
                        MDIconButton:
                                id:seat54
                                name:"B54"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B54")
                                pos_hint:{"center_x":0.74,"center_y":0.3}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.6,"center_y":0.27}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.67,"center_y":0.27}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.74,"center_y":0.27}

                        MDIconButton:
                                id:seat58
                                name:"B58"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B58")
                                pos_hint:{"center_x":0.6,"center_y":0.25}
                        MDIconButton:
                                id:seat59
                                name:"B59"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B59")
                                pos_hint:{"center_x":0.67,"center_y":0.25}
                        MDIconButton:
                                id:seat60
                                name:"B60"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B60")
                                pos_hint:{"center_x":0.74,"center_y":0.25}
                        #sixth row
                        MDIconButton:
                                id:seat61
                                name:"B61"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B61")
                                pos_hint:{"center_x":0.1,"center_y":0.2}
                        MDIconButton:
                                id:seat62
                                name:"B62"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B62")
                                pos_hint:{"center_x":0.17,"center_y":0.2}
                        MDIconButton:
                                id:seat63
                                name:"B63"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B63")
                                pos_hint:{"center_x":0.24,"center_y":0.2}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.1,"center_y":0.17}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.17,"center_y":0.17}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.24,"center_y":0.17}
                        MDIconButton:
                                id:seat67
                                name:"B67"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B67")
                                pos_hint:{"center_x":0.1,"center_y":0.15}
                        MDIconButton:
                                id:seat68
                                name:"B68"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B68")
                                pos_hint:{"center_x":0.174,"center_y":0.15}
                        MDIconButton:
                                id:seat69
                                name:"B69"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B69")
                                pos_hint:{"center_x":0.24,"center_y":0.15}
                        MDIconButton:
                                id:seat64
                                name:"B64"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B64")
                                pos_hint:{"center_x":0.6,"center_y":0.2}
                        MDIconButton:
                                id:seat65
                                name:"B65"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B65")
                                pos_hint:{"center_x":0.67,"center_y":0.2}
                        MDIconButton:
                                id:seat66
                                name:"B66"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B66")
                                pos_hint:{"center_x":0.74,"center_y":0.2}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.6,"center_y":0.17}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.67,"center_y":0.17}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.74,"center_y":0.17}

                        MDIconButton:
                                id:seat70
                                name:"B70"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B70")
                                pos_hint:{"center_x":0.6,"center_y":0.15}
                        MDIconButton:
                                id:seat71
                                name:"B71"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B71")
                                pos_hint:{"center_x":0.67,"center_y":0.15}
                        MDIconButton:
                                id:seat72
                                name:"B72"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B72")
                                pos_hint:{"center_x":0.74,"center_y":0.15}
                        #seventh row
                        MDIconButton:
                                id:seat73
                                name:"B73"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B73")
                                pos_hint:{"center_x":0.1,"center_y":0.1}
                        MDIconButton:
                                id:seat74
                                name:"B74"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B74")
                                pos_hint:{"center_x":0.17,"center_y":0.1}
                        MDIconButton:
                                id:seat75
                                name:"B75"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B75")
                                pos_hint:{"center_x":0.24,"center_y":0.1}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.1,"center_y":0.07}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.17,"center_y":0.07}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.24,"center_y":0.07}
                        MDIconButton:
                                id:seat79
                                name:"B79"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B79")
                                pos_hint:{"center_x":0.1,"center_y":0.05}
                        MDIconButton:
                                id:seat80
                                name:"B80"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B80")
                                pos_hint:{"center_x":0.17,"center_y":0.05}
                        MDIconButton:
                                id:seat81
                                name:"B81"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B81")
                                pos_hint:{"center_x":0.24,"center_y":0.05}
                        MDIconButton:
                                id:seat76
                                name:"B76"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B76")
                                pos_hint:{"center_x":0.6,"center_y":0.1}
                        MDIconButton:
                                id:seat77
                                name:"B77"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B77")
                                pos_hint:{"center_x":0.67,"center_y":0.1}
                        MDIconButton:
                                id:seat78
                                name:"B78"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B78")
                                pos_hint:{"center_x":0.74,"center_y":0.1}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.6,"center_y":0.07}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.67,"center_y":0.07}
                        MDIconButton:
                                icon: "rectangle"
                                theme_text_color: "Custom"
                                text_color: "#A55A5A"
                                pos_hint:{"center_x":0.74,"center_y":0.07}

                        MDIconButton:
                                id:seat82
                                name:"B82"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B82")
                                pos_hint:{"center_x":0.6,"center_y":0.05}
                        MDIconButton:
                                id:seat83
                                name:"B83"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B83")
                                pos_hint:{"center_x":0.67,"center_y":0.05}
                        MDIconButton:
                                id:seat84
                                name:"B84"
                                icon: "seat"
                                on_release:app.check_seat_availability2("B84")
                                pos_hint:{"center_x":0.74,"center_y":0.05}
